---
title: "renewal2"
author: "Sarah Deussing"
date: "2025-04-25"
output: html_document
---

## Data
```{r}
library(readxl)
account_status <- read.csv('data/reds_wheelhouse_edw_nd_account_status.csv')
buyer_types <- read_excel('data/reds_wheelhouse_edw_nd_buyer_types.xlsx')
demographics <- read.csv('data/reds_wheelhouse_edw_nd_demographics.csv')
promotions <- read.csv('data/reds_wheelhouse_edw_nd_promotions.csv')
ticket_sales <- read.csv('data/reds_wheelhouse_edw_nd_ticket_sales_3.csv')
buyer_behavior = read.csv("sum_tickets.csv") 
```


## Count Changes to Purchases by Year (Renew Behavior)
```{r}
library(dplyr)
tenure <- account_status %>% group_by(ACCOUNT_KEY) %>% 
  filter(max(TENURE) > 1) %>% 
  arrange(ACCOUNT_KEY, SEASON_YEAR, FIRST_PURCHASE_DATE) %>%
  select(ACCOUNT_KEY, SEASON_YEAR) %>% distinct()

tenure <- merge(tenure, ticket_sales[, c("ACCOUNT_KEY", "SEASON_YEAR", "BUYER_TYPE_CODE")], 
                by = c("ACCOUNT_KEY", "SEASON_YEAR"), all.x = TRUE)

tenure <- tenure %>%
  group_by(ACCOUNT_KEY, SEASON_YEAR) %>%
  summarise(BUYER_TYPE_CODE = paste(unique(BUYER_TYPE_CODE), collapse = ", "), .groups = 'drop')

tenure2 <- tenure %>% filter(BUYER_TYPE_CODE != "NA")
tenure2$TENURE <- tenure2$RENEWED <- tenure2$KEPT_CODES <- tenure2$UNKEPT_CODES <- NA

tenure2$GENERAL_BUYER_CODE <- sapply(strsplit(tenure2$BUYER_TYPE_CODE, ","), function(x) {
  x_trimmed <- trimws(x)
  x_short <- vapply(x_trimmed, function(word) substr(word, 1, 3), character(1))
  x_unique <- unique(x_short)
  paste(x_unique, collapse = ",")
})
```

```{r}
tenure2 <- tenure2 %>% select(-BUYER_TYPE_CODE)
```


```{r}
renew_behavior <- data.frame(ACCOUNT_KEY = character(),
                             SEASON_YEAR = numeric(),
                             GENERAL_BUYER_CODE = character(),
                             TENURE = numeric(),
                             RENEWED = numeric(),
                             KEPT_CODES = character(),
                             UNKEPT_CODES = character())

accounts <- unique(tenure2$ACCOUNT_KEY)

for (a in accounts) {
    temp <- tenure2[tenure2$ACCOUNT_KEY == a, ]
    temp <- temp[order(temp$SEASON_YEAR), ]
    
    years <- unique(temp$SEASON_YEAR)
    all_years <- seq(from = min(temp$SEASON_YEAR), to = max(temp$SEASON_YEAR), by = 1)
    missing <- setdiff(all_years, years)
    if (length(missing) > 0) {
      df <- data.frame(ACCOUNT_KEY = rep(a, length(missing)), SEASON_YEAR = missing,
                       GENERAL_BUYER_CODE = rep(NA, length(missing)), TENURE = rep(NA, length(missing)), 
                       RENEWED = rep(NA, length(missing)), 
                       KEPT_CODES = rep(NA, length(missing)), UNKEPT_CODES = rep(NA, length(missing)))
      temp <- rbind(temp, df)
      temp <- temp[order(temp$SEASON_YEAR), ]
    }
  
    # new columns
    renewed <- rep(0, nrow(temp))
    tenured <- rep(1, nrow(temp))
    kept_codes <- unkept_codes <- rep(NA, nrow(temp))
    renew_val <- 0
    tenure_val <- 1
    for (i in 1: nrow(temp)) {
      if (i == 1) {renew_val <- 0 
                  tenure_val <- 1}
      else {
        
        # if they purchased something that year (buyer code is not NA)
        if (!is.na(temp$GENERAL_BUYER_CODE[i])) { 
          tenure_val <- tenure_val + 1 # increment tenure val
          
          curr_codes <- unlist(strsplit(temp$GENERAL_BUYER_CODE[i], ","))
          prev_codes <- unlist(strsplit(temp$GENERAL_BUYER_CODE[i-1], ","))
        
          kept_codes[i] <- paste(intersect(curr_codes, prev_codes), collapse = ",")
          unkept_codes[i] <- paste(setdiff(curr_codes, prev_codes), collapse = ",")
        
          # increment renew val
          if (length(intersect(curr_codes, prev_codes)) > 0) { renew_val <- renew_val + 1 }
          else { renew_val <-  0 }
        }
        
        # they did not purchase anything
        else {tenure_val <- 1 
              renew_val <- 0
              kept_codes[i] <- "none"
              unkept_codes[i] <- "none"}
      }
      
      renewed[i] <- renew_val
      tenured[i] <- tenure_val
    }
    temp$RENEWED <- renewed
    temp$TENURE <- tenured
    temp$KEPT_CODES <- kept_codes
    temp$UNKEPT_CODES <- unkept_codes
    
    renew_behavior <- rbind(renew_behavior, 
                            temp[, c("ACCOUNT_KEY", "SEASON_YEAR", "GENERAL_BUYER_CODE", "TENURE", "RENEWED", 
                                     "KEPT_CODES", "UNKEPT_CODES")])
}
```

Stats
```{r}
# most common kept code
kept_codes_table <- table(renew_behavior$KEPT_CODES[!renew_behavior$KEPT_CODES %in% c("", "none")])
names(kept_codes_table)[which.max(kept_codes_table)]

# most common unkept code
unkept_codes_table <- table(renew_behavior$UNKEPT_CODES[!renew_behavior$UNKEPT_CODES %in% c("", "none")])
names(unkept_codes_table)[which.max(unkept_codes_table)]
```

```{r}
# longest tenure
renew_behavior[which.max(renew_behavior$TENURE), c("ACCOUNT_KEY", "TENURE")]

# longest renew
renew_behavior[which.max(renew_behavior$RENEWED), c("ACCOUNT_KEY", "RENEWED", "KEPT_CODES")]
```


## Last general code of churners
```{r}
ticket_sales$GENERAL_BUYER_CODE <- substr(ticket_sales$BUYER_TYPE_CODE, 1, 3)
```

```{r}
latest_season <- max(ticket_sales$SEASON_YEAR, na.rm = TRUE)

account_last_seen <- ticket_sales %>%
  filter(!is.na(GENERAL_BUYER_CODE)) %>%
  group_by(ACCOUNT_KEY) %>%
  arrange(SEASON_YEAR) %>%
  mutate(
    Last_Active_Season = last(SEASON_YEAR),
    .groups = "drop"
  ) %>% group_by(ACCOUNT_KEY, SEASON_YEAR) %>%
  mutate(
    Last_GENERAL_BUYER_CODE = last(GENERAL_BUYER_CODE),
    perc_use = sum(SCAN_COUNT, na.rm = TRUE) / n(),
    total_count = n(),
    mode_price_scale = mode(factor(PRICE_SCALE_DESCRIPTION))
  ) %>% 
  select(ACCOUNT_KEY, SEASON_YEAR, Last_Active_Season, Last_GENERAL_BUYER_CODE, ACCOUNT_TYPE, perc_use, total_count) %>%
  arrange(ACCOUNT_KEY, SEASON_YEAR) %>% distinct()

account_last_seen <- account_last_seen %>% group_by(ACCOUNT_KEY, SEASON_YEAR) %>%
  mutate(Churned = (Last_Active_Season == SEASON_YEAR) && !(latest_season == SEASON_YEAR))

churners <- account_last_seen %>% 
  filter(Churned== "TRUE") %>% 
  mutate(Years_Gone=latest_season-Last_Active_Season)
```


Top Churn Codes
```{r}
top_churn_codes <- churners %>% ungroup() %>%
  count(Last_GENERAL_BUYER_CODE) %>%
  arrange(desc(n)) %>% 
  slice_head(n=10)

desc <- data.frame(Last_GENERAL_BUYER_CODE = top_churn_codes$Last_GENERAL_BUYER_CODE, Description = c("Pick 6", "Full price ticket", "Full NP new", "Full NP renew/upgrade", "Flex pack", "Holiday flex pack", "Full exchange", "Day of game", "Front Row", "Full PR new"))
top_churn_codes <- merge(top_churn_codes, desc)

top_churn_codes %>% arrange(desc(n)) 
```

Top churned codes are pick 6, full price tickets, and flex pack tickets.
```{r}
get_mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}
```

```{r}
sales_demo <- merge(ticket_sales, demographics, by = "ACCOUNT_KEY")
```

```{r}
churn_codes_ranked <- churners %>%
  group_by(Last_GENERAL_BUYER_CODE) %>%
  summarize(count = n()) %>% arrange(desc(count)) %>%
  mutate(churn_rank = row_number()) %>%
  rename(GENERAL_BUYER_CODE = Last_GENERAL_BUYER_CODE)

sales_demo2 <- merge(sales_demo, churn_codes_ranked, by = "GENERAL_BUYER_CODE")
#write.csv(sales_demo2, "sales_and_churn.csv")
```

```{r, warning = FALSE}
sales_demo %>% filter(GENERAL_BUYER_CODE %in% top_churn_codes$Last_GENERAL_BUYER_CODE) %>%
  group_by(GENERAL_BUYER_CODE) %>%
  summarize(avg_age = mean(AGE, na.rm = TRUE),
            mean_income_mid = mean(INCOME_MIDPOINT, na.rm = TRUE),
            seat_section_avg = mean(as.numeric(SEAT_SECTION), na.rm = TRUE),
            seat_row_avg = get_mode(SEAT_ROW),
            zip_code_mode = get_mode(ZIP_CODE),
            city_mode = get_mode(CITY),
            state_mode = get_mode(STATE),
            opp_mode = get_mode(OPPONENT))
```


