---
title: "renewal_analysis"
author: "Sarah Deussing"
date: "2025-04-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data
```{r}
library(readxl)
account_status <- read.csv('reds_wheelhouse_edw_nd_account_status.csv')
buyer_types <- read_excel('reds_wheelhouse_edw_nd_buyer_types.xlsx')
demographics <- read.csv('reds_wheelhouse_edw_nd_demographics.csv')
promotions <- read.csv('reds_wheelhouse_edw_nd_promotions.csv')
ticket_sales <- read.csv('reds_wheelhouse_edw_nd_ticket_sales_3.csv')
```

## Find tenured customers
```{r}
library(dplyr)
tenure <- account_status %>% group_by(ACCOUNT_KEY) %>% 
  filter(max(TENURE) > 1) %>% 
  arrange(ACCOUNT_KEY, SEASON_YEAR, FIRST_PURCHASE_DATE) %>%
  select(ACCOUNT_KEY, SEASON_YEAR) %>% distinct()

tenure <- merge(tenure, ticket_sales[, c("ACCOUNT_KEY", "SEASON_YEAR", "BUYER_TYPE_CODE")], 
                by = c("ACCOUNT_KEY", "SEASON_YEAR"), all.x = TRUE)

tenure <- tenure %>%
  group_by(ACCOUNT_KEY, SEASON_YEAR) %>%
  summarise(BUYER_TYPE_CODE = paste(unique(BUYER_TYPE_CODE), collapse = ", "), .groups = 'drop')

tenure2 <- tenure %>% filter(BUYER_TYPE_CODE != "NA")
tenure2$TENURE <- tenure2$RENEWED <- tenure2$KEPT_CODES <- tenure2$UNKEPT_CODES <- NA
```

## Count Changes to Purchases by Year
```{r}
renew_behavior <- data.frame(ACCOUNT_KEY = character(),
                             SEASON_YEAR = numeric(),
                             BUYER_TYPE_CODE = character(),
                             TENURE = numeric(),
                             RENEWED = numeric(),
                             KEPT_CODES = character(),
                             UNKEPT_CODES = character())

accounts <- unique(tenure2$ACCOUNT_KEY)

for (a in accounts) {
    temp <- tenure2[tenure2$ACCOUNT_KEY == a, ]
    temp <- temp[order(temp$SEASON_YEAR), ]
    
    years <- unique(temp$SEASON_YEAR)
    all_years <- seq(from = min(temp$SEASON_YEAR), to = max(temp$SEASON_YEAR), by = 1)
    missing <- setdiff(all_years, years)
    if (length(missing) > 0) {
      df <- data.frame(ACCOUNT_KEY = rep(a, length(missing)), SEASON_YEAR = missing,
                       BUYER_TYPE_CODE = rep(NA, length(missing)), TENURE = rep(NA, length(missing)), 
                       RENEWED = rep(NA, length(missing)), 
                       KEPT_CODES = rep(NA, length(missing)), UNKEPT_CODES = rep(NA, length(missing)))
      temp <- rbind(temp, df)
      temp <- temp[order(temp$SEASON_YEAR), ]
    }
  
    # new columns
    renewed <- rep(0, nrow(temp))
    tenured <- rep(1, nrow(temp))
    kept_codes <- unkept_codes <- rep(NA, nrow(temp))
    renew_val <- 0
    tenure_val <- 1
    for (i in 1: nrow(temp)) {
      if (i == 1) {renew_val <- 0 
                  tenure_val <- 1}
      else {
        
        # if they purchased something that year (buyer code is not NA)
        if (!is.na(temp$BUYER_TYPE_CODE[i])) { 
          tenure_val <- tenure_val + 1 # increment tenure val
          
          curr_codes <- unlist(strsplit(temp$BUYER_TYPE_CODE[i], ", "))
          prev_codes <- unlist(strsplit(temp$BUYER_TYPE_CODE[i-1], ", "))
        
          kept_codes[i] <- paste(intersect(curr_codes, prev_codes), collapse = ", ")
          unkept_codes[i] <- paste(setdiff(curr_codes, prev_codes), collapse = ", ")
        
          # increment renew val
          if (length(intersect(curr_codes, prev_codes) > 0)) { renew_val <- renew_val + 1 }
          else { renew_val <-  0 }
        }
        
        # they did not purchase anything
        else {tenure_val <- 1 
              renew_val <- 0
              kept_codes[i] <- "none"
              unkept_codes[i] <- "none"}
      }
      
      renewed[i] <- renew_val
      tenured[i] <- tenure_val
    }
    temp$RENEWED <- renewed
    temp$TENURE <- tenured
    temp$KEPT_CODES <- kept_codes
    temp$UNKEPT_CODES <- unkept_codes
    
    renew_behavior <- rbind(renew_behavior, 
                            temp[, c("ACCOUNT_KEY", "SEASON_YEAR", "BUYER_TYPE_CODE", "TENURE", "RENEWED", 
                                     "KEPT_CODES", "UNKEPT_CODES")])
}
```

Stats
```{r}
# most common kept code
kept_codes_table <- table(renew_behavior$KEPT_CODES[!renew_behavior$KEPT_CODES %in% c("", "none")])
names(kept_codes_table)[which.max(kept_codes_table)]

# most common unkept code
unkept_codes_table <- table(renew_behavior$UNKEPT_CODES[!renew_behavior$UNKEPT_CODES %in% c("", "none")])
names(unkept_codes_table)[which.max(unkept_codes_table)]
```

```{r}
# longest tenure
renew_behavior[which.max(renew_behavior$TENURE), c("ACCOUNT_KEY", "TENURE")]

# longest renew
renew_behavior[which.max(renew_behavior$RENEWED), c("ACCOUNT_KEY", "RENEWED", "KEPT_CODES")]
```

Demographics of Renewing/Moving
```{r}
library(tidyr)
renew_behavior_demo <- renew_behavior %>%
  left_join(demographics, by = "ACCOUNT_KEY")

renew_behavior_demo <- renew_behavior_demo %>%
  mutate(AGE_GROUP = cut(AGE, breaks = c(0, 25, 35, 50, 65, 100),
                    labels = c("Under 25", "25–35", "36–50", "51–65", "65+")))


top10_age <- renew_behavior_demo %>%
  filter(!is.na(BUYER_TYPE_CODE) & !is.na(AGE_GROUP)) %>%
  group_by(AGE_GROUP, BUYER_TYPE_CODE) %>%
  summarise(Count = n(), .groups = 'drop') %>%
  arrange(AGE_GROUP, desc(Count)) %>%
  group_by(AGE_GROUP) %>%
  slice_head(n = 10)

location_behavior <- renew_behavior %>%
  left_join(ticket_sales %>% select(ACCOUNT_KEY, SEASON_YEAR, CITY, STATE),
            by = c("ACCOUNT_KEY", "SEASON_YEAR"))
location_behavior <- location_behavior %>%
  separate_rows(BUYER_TYPE_CODE, sep = ",\\s*") %>%
  filter(!is.na(BUYER_TYPE_CODE) & !is.na(CITY) & !is.na(STATE)) %>%
  group_by(CITY, STATE, BUYER_TYPE_CODE) %>%
  summarise(Count = n(), .groups = 'drop')
```

## Use %
```{r}
# overall
ticket_use_perc <- sum(ticket_sales$SCAN_COUNT, na.rm = TRUE) / nrow(ticket_sales)
ticket_use_perc

# by year
ticket_use_yearly <- ticket_sales %>%
  select(SEASON_YEAR, SCAN_COUNT) %>%
  group_by(SEASON_YEAR) %>%
  summarize(perc_use = sum(SCAN_COUNT, na.rm = TRUE) / n())
ticket_use_yearly

# by game
ticket_use_by_game <- ticket_sales %>%
  select(EVENT_NAME, SCAN_COUNT) %>%
  group_by(EVENT_NAME) %>%
  summarize(perc_use = sum(SCAN_COUNT, na.rm = TRUE) / n()) %>% arrange(desc(perc_use))
ticket_use_by_game

# by buyer type code
ticket_use_by_code <- ticket_sales %>%
  select(BUYER_TYPE_CODE, SCAN_COUNT) %>%
  group_by(BUYER_TYPE_CODE) %>%
  summarize(perc_use = sum(SCAN_COUNT, na.rm = TRUE) / n(),
            total_count = n()) %>% arrange(desc(total_count))
ticket_use_by_code
```

